import {
  GiftMember,
  GoldAsset,
  GoldAccount,
  TransactionOrder,
  VaultSite,
  LogisticsServiceProvider,
  GiftUser,
  TransactionEvent,
} from "@/types";

// Generate mock GIFT Members
export const mockMembers: GiftMember[] = [
  {
    member_gic: "GOLDBNK1",
    entity_name: "Swiss Gold Bank SA",
    type_member: "Bullion Bank",
    country: "Switzerland",
    member_roles: ["ROLE_TRADER", "ROLE_CUSTODIAN", "ROLE_VAULT_OP"],
    current_member_status: "Active",
    membership_effective_date: "2022-01-15",
    contact_email: "contact@swissgoldbank.ch",
    contact_phone: "+41 22 123 4567",
    city: "Zurich",
    website: "www.swissgoldbank.ch",
  },
  {
    member_gic: "VALCMBY1",
    entity_name: "Valcambi SA",
    type_member: "Refinery",
    country: "Switzerland",
    member_roles: ["ROLE_REFINER", "ROLE_MINTER"],
    current_member_status: "Active",
    membership_effective_date: "2022-02-20",
    contact_email: "info@valcambi.ch",
    city: "Balerna",
    website: "www.valcambi.com",
  },
  {
    member_gic: "DUBAGLD1",
    entity_name: "Dubai Gold Trading DMCC",
    type_member: "Gold Trader",
    country: "United Arab Emirates",
    member_roles: ["ROLE_TRADER", "ROLE_CUSTODIAN"],
    current_member_status: "Active",
    membership_effective_date: "2022-03-10",
    contact_email: "trade@dubaigold.ae",
    city: "Dubai",
  },
  {
    member_gic: "LNDONVLT",
    entity_name: "London Vault Services Ltd",
    type_member: "Gold Custodian",
    country: "United Kingdom",
    member_roles: ["ROLE_CUSTODIAN", "ROLE_VAULT_OP"],
    current_member_status: "Active",
    membership_effective_date: "2022-04-05",
    contact_email: "custody@londonvault.co.uk",
    city: "London",
  },
  {
    member_gic: "PRTHMNT",
    entity_name: "Perth Mint",
    type_member: "Refinery",
    country: "Australia",
    member_roles: ["ROLE_REFINER", "ROLE_MINTER", "ROLE_CUSTODIAN"],
    current_member_status: "Active",
    membership_effective_date: "2022-05-12",
    contact_email: "contact@perthmint.com.au",
    city: "Perth",
  },
];

// Generate mock Gold Assets (NFTs)
export const mockAssets: GoldAsset[] = [
  {
    token_id: "0x7f8a9b3c5e4d6f2a1b8c9d0e3f5a7b4c",
    gift_bullion_id: "VALCAMBY-SN-100234",
    traceability_gic: "VALCMBY1",
    refiner_name: "Valcambi SA",
    serial_number: "SN-100234",
    gold_product_type_id: "GOLD_BAR_1KG",
    fineness: 999.9,
    weight_grams: 1000,
    asset_value_at_minting: 64000,
    gold_rate_at_minting: 64.0,
    custody_party_type: "Member",
    custody_party_id: "GOLDBNK1",
    asset_status: "IN_VAULT",
    blockchain_status: "Minted",
    created_on_chain_at: "2024-01-15T10:30:00Z",
    last_on_chain_update: "2024-01-15T10:30:00Z",
  },
  {
    token_id: "0x3e9f2d8c6b7a4e1f0c5d9a8b2f4e6c3a",
    gift_bullion_id: "PRTHMNT-AU-992847",
    traceability_gic: "PRTHMNT",
    refiner_name: "Perth Mint",
    serial_number: "AU-992847",
    gold_product_type_id: "GOLD_BAR_400OZ",
    fineness: 999.5,
    weight_grams: 12441.39,
    asset_value_at_minting: 796250,
    gold_rate_at_minting: 64.0,
    custody_party_type: "Member",
    custody_party_id: "LNDONVLT",
    asset_status: "IN_VAULT",
    blockchain_status: "Minted",
    created_on_chain_at: "2024-02-20T14:15:00Z",
    last_on_chain_update: "2024-02-20T14:15:00Z",
  },
  {
    token_id: "0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d",
    gift_bullion_id: "VALCAMBY-SN-100235",
    traceability_gic: "VALCMBY1",
    refiner_name: "Valcambi SA",
    serial_number: "SN-100235",
    gold_product_type_id: "GOLD_BAR_1KG",
    fineness: 999.9,
    weight_grams: 1000,
    asset_value_at_minting: 64500,
    gold_rate_at_minting: 64.5,
    custody_party_type: "Member",
    custody_party_id: "DUBAGLD1",
    asset_status: "IN_TRANSIT",
    blockchain_status: "Transferred",
    created_on_chain_at: "2024-03-10T09:00:00Z",
    last_on_chain_update: "2024-03-15T11:30:00Z",
  },
  {
    token_id: "0x9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b",
    gift_bullion_id: "VALCAMBY-SN-100236",
    traceability_gic: "VALCMBY1",
    refiner_name: "Valcambi SA",
    serial_number: "SN-100236",
    gold_product_type_id: "GOLD_BAR_500G",
    fineness: 999.9,
    weight_grams: 500,
    asset_value_at_minting: 32250,
    gold_rate_at_minting: 64.5,
    custody_party_type: "Member",
    custody_party_id: "GOLDBNK1",
    asset_status: "PLEDGED",
    blockchain_status: "Minted",
    created_on_chain_at: "2024-04-05T13:45:00Z",
    last_on_chain_update: "2024-04-10T16:20:00Z",
  },
];

// Generate more assets
for (let i = 5; i <= 25; i++) {
  const statuses: GoldAsset["asset_status"][] = [
    "IN_VAULT",
    "IN_TRANSIT",
    "PLEDGED",
    "LOCKED",
  ];
  const refiners = ["VALCMBY1", "PRTHMNT"];
  const refinerNames = ["Valcambi SA", "Perth Mint"];
  const refinerIndex = i % 2;

  mockAssets.push({
    token_id: `0x${Math.random().toString(16).substr(2, 32)}`,
    gift_bullion_id: `${refiners[refinerIndex]}-SN-${100200 + i}`,
    traceability_gic: refiners[refinerIndex],
    refiner_name: refinerNames[refinerIndex],
    serial_number: `SN-${100200 + i}`,
    gold_product_type_id: i % 3 === 0 ? "GOLD_BAR_1KG" : "GOLD_BAR_500G",
    fineness: 999.9,
    weight_grams: i % 3 === 0 ? 1000 : 500,
    asset_value_at_minting: (i % 3 === 0 ? 1000 : 500) * 64.5,
    gold_rate_at_minting: 64.5,
    custody_party_type: "Member",
    custody_party_id: ["GOLDBNK1", "DUBAGLD1", "LNDONVLT"][i % 3],
    asset_status: statuses[i % statuses.length],
    blockchain_status: "Minted",
    created_on_chain_at: new Date(2024, 0, i).toISOString(),
    last_on_chain_update: new Date(2024, 0, i + 1).toISOString(),
  });
}

// Generate mock Gold Accounts
export const mockAccounts: GoldAccount[] = [
  {
    igan: "GIFT-CH-GOLDBNK1-001-0001",
    managing_member_gic: "GOLDBNK1",
    holder_type: "Member",
    holder_id: "DUBAGLD1",
    vault_site_id: "VS-ZRH-001",
    vault_id: "VAULT-A1",
    gold_account_status: "Active",
    allocation_mode: "Allocated",
    guarantee_deposit_account: false,
    total_gold_assets: 5,
    total_weight_grams: 5000,
    total_fine_weight_grams: 4999.5,
    total_valuation_currency: "USD",
    total_valuation_amount: 322500,
  },
  {
    igan: "GIFT-AE-DUBAGLD1-002-0001",
    managing_member_gic: "DUBAGLD1",
    holder_type: "Member",
    holder_id: "DUBAGLD1",
    vault_site_id: "VS-DXB-001",
    vault_id: "VAULT-B2",
    gold_account_status: "Active",
    allocation_mode: "Allocated",
    guarantee_deposit_account: false,
    total_gold_assets: 3,
    total_weight_grams: 2500,
    total_fine_weight_grams: 2499.75,
    total_valuation_currency: "USD",
    total_valuation_amount: 161250,
  },
  {
    igan: "GIFT-GB-LNDONVLT-003-0001",
    managing_member_gic: "LNDONVLT",
    holder_type: "Member",
    holder_id: "GOLDBNK1",
    vault_site_id: "VS-LON-001",
    vault_id: "VAULT-C3",
    gold_account_status: "Active",
    allocation_mode: "Unallocated",
    guarantee_deposit_account: true,
    total_gold_assets: 10,
    total_weight_grams: 12441.39,
    total_fine_weight_grams: 12435.17,
    total_valuation_currency: "USD",
    total_valuation_amount: 802265,
  },
];

// Generate more accounts
for (let i = 4; i <= 12; i++) {
  mockAccounts.push({
    igan: `GIFT-CH-GOLDBNK1-00${i}-0001`,
    managing_member_gic: "GOLDBNK1",
    holder_type: i % 2 === 0 ? "Member" : "End_Customer",
    holder_id: i % 2 === 0 ? "DUBAGLD1" : `CUSTOMER-${i}`,
    vault_site_id: "VS-ZRH-001",
    vault_id: `VAULT-A${i}`,
    gold_account_status: "Active",
    allocation_mode: i % 2 === 0 ? "Allocated" : "Unallocated",
    guarantee_deposit_account: false,
    total_gold_assets: Math.floor(Math.random() * 10) + 1,
    total_weight_grams: Math.floor(Math.random() * 10000) + 1000,
    total_fine_weight_grams: Math.floor(Math.random() * 10000) + 1000,
    total_valuation_currency: "USD",
    total_valuation_amount: Math.floor(Math.random() * 500000) + 50000,
  });
}

// Generate mock Transactions
export const mockTransactions: TransactionOrder[] = [
  {
    transaction_reference: "TX-A1B2C",
    transaction_type: "Transfer",
    transaction_status: "Settled",
    sender_igan: "GIFT-CH-GOLDBNK1-001-0001",
    receiver_igan: "GIFT-AE-DUBAGLD1-002-0001",
    initiator_gic: "GOLDBNK1",
    counterparty_gic: "DUBAGLD1",
    cargo_weight_grams: 1000,
    cargo_fineness_millieme: 999,
    transaction_value: 64500,
    valuation_currency: "USD",
    initiation_timestamp: "2024-01-10T08:00:00Z",
    completion_timestamp: "2024-01-15T14:30:00Z",
    assets: ["0x7f8a9b3c5e4d6f2a1b8c9d0e3f5a7b4c"],
  },
  {
    transaction_reference: "TX-D3E4F",
    transaction_type: "Transfer",
    transaction_status: "In execution",
    sender_igan: "GIFT-AE-DUBAGLD1-002-0001",
    receiver_igan: "GIFT-GB-LNDONVLT-003-0001",
    initiator_gic: "DUBAGLD1",
    counterparty_gic: "LNDONVLT",
    cargo_weight_grams: 500,
    cargo_fineness_millieme: 999,
    transaction_value: 32250,
    valuation_currency: "USD",
    initiation_timestamp: "2024-03-01T10:00:00Z",
    assets: ["0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d"],
  },
  {
    transaction_reference: "TX-G5H6I",
    transaction_type: "Purchase",
    transaction_status: "Approved by Counterparty",
    sender_igan: "GIFT-GB-LNDONVLT-003-0001",
    receiver_igan: "GIFT-CH-GOLDBNK1-001-0001",
    initiator_gic: "LNDONVLT",
    counterparty_gic: "GOLDBNK1",
    cargo_weight_grams: 2000,
    cargo_fineness_millieme: 999,
    transaction_value: 129000,
    valuation_currency: "USD",
    initiation_timestamp: "2024-03-10T09:15:00Z",
  },
];

// Generate more transactions
const txStatuses: TransactionOrder["transaction_status"][] = [
  "Draft",
  "Created",
  "Submitted for approval",
  "Approved by Counterparty",
  "In execution",
  "Settled",
  "Closed",
];

for (let i = 4; i <= 18; i++) {
  mockTransactions.push({
    transaction_reference: `TX-${Math.random().toString(36).substr(2, 5).toUpperCase()}`,
    transaction_type: i % 3 === 0 ? "Purchase" : "Transfer",
    transaction_status: txStatuses[i % txStatuses.length],
    sender_igan: mockAccounts[i % mockAccounts.length].igan,
    receiver_igan: mockAccounts[(i + 1) % mockAccounts.length].igan,
    initiator_gic: mockMembers[i % mockMembers.length].member_gic,
    counterparty_gic: mockMembers[(i + 1) % mockMembers.length].member_gic,
    cargo_weight_grams: [500, 1000, 2000][i % 3],
    cargo_fineness_millieme: 999,
    transaction_value: [500, 1000, 2000][i % 3] * 64.5,
    valuation_currency: "USD",
    initiation_timestamp: new Date(2024, 2, i).toISOString(),
    completion_timestamp:
      i % 3 === 0 ? new Date(2024, 2, i + 5).toISOString() : undefined,
  });
}

// Generate mock Vault Sites
export const mockVaultSites: VaultSite[] = [
  {
    vault_site_id: "VS-ZRH-001",
    vault_site_name: "Zurich Secure Vault",
    member_gic: "GOLDBNK1",
    location_name: "Zurich Banking District",
    city: "Zurich",
    country: "Switzerland",
    number_of_vaults: 5,
    maximum_weight_ingold_kg: 50000,
    insurance_coverage_name_of_insurer: "Swiss Re",
    insurance_coverage_expiration_date: "2025-12-31",
    last_audit_date: "2024-01-15",
  },
  {
    vault_site_id: "VS-DXB-001",
    vault_site_name: "Dubai Gold Vault DMCC",
    member_gic: "DUBAGLD1",
    location_name: "DMCC Gold & Commodities Tower",
    city: "Dubai",
    country: "United Arab Emirates",
    number_of_vaults: 3,
    maximum_weight_ingold_kg: 30000,
    insurance_coverage_name_of_insurer: "Lloyds of London",
    insurance_coverage_expiration_date: "2025-06-30",
    last_audit_date: "2024-02-10",
  },
  {
    vault_site_id: "VS-LON-001",
    vault_site_name: "London Vault Services",
    member_gic: "LNDONVLT",
    location_name: "City of London",
    city: "London",
    country: "United Kingdom",
    number_of_vaults: 4,
    maximum_weight_ingold_kg: 40000,
    insurance_coverage_name_of_insurer: "Lloyds of London",
    insurance_coverage_expiration_date: "2025-09-30",
    last_audit_date: "2024-01-20",
  },
];

// Generate mock LSPs
export const mockLSPs: LogisticsServiceProvider[] = [
  {
    lsp_id: "LSP-001",
    lsp_name: "Brinks Global Logistics",
    lsp_type: "Armored Transport",
    legal_entity_name: "Brinks International Ltd",
    incorporation_country: "United States",
    lsp_status: "Active",
    countries_of_operations: ["United States", "United Kingdom", "Switzerland", "UAE", "Singapore"],
    weight_limit_kg: 10000,
  },
  {
    lsp_id: "LSP-002",
    lsp_name: "Loomis International",
    lsp_type: "Secure Transport",
    legal_entity_name: "Loomis AB",
    incorporation_country: "Sweden",
    lsp_status: "Active",
    countries_of_operations: ["Sweden", "Norway", "Denmark", "United Kingdom", "Germany"],
    weight_limit_kg: 8000,
  },
];

// Generate mock Users
export const mockUsers: GiftUser[] = [
  {
    user_id: "USER-001",
    entity_type: "Member",
    entity_id: "GOLDBNK1",
    email: "john.doe@swissgoldbank.ch",
    first_name: "John",
    last_name: "Doe",
    job_title: "Operations Manager",
    status: "Active",
    last_login_at: "2024-03-15T08:30:00Z",
    roles: ["ROLE_TRADER", "ROLE_CUSTODIAN"],
  },
  {
    user_id: "USER-002",
    entity_type: "Member",
    entity_id: "DUBAGLD1",
    email: "ahmed.ali@dubaigold.ae",
    first_name: "Ahmed",
    last_name: "Ali",
    job_title: "Trading Director",
    status: "Active",
    last_login_at: "2024-03-14T12:45:00Z",
    roles: ["ROLE_TRADER"],
  },
  {
    user_id: "USER-003",
    entity_type: "GMO",
    email: "admin@giftplatform.org",
    first_name: "Platform",
    last_name: "Administrator",
    job_title: "System Administrator",
    status: "Active",
    last_login_at: "2024-03-15T09:00:00Z",
    roles: ["ROLE_PLATFORM", "ROLE_GOVERNANCE"],
  },
];

// Generate more users
for (let i = 4; i <= 12; i++) {
  mockUsers.push({
    user_id: `USER-00${i}`,
    entity_type: "Member",
    entity_id: mockMembers[i % mockMembers.length].member_gic,
    email: `user${i}@example.com`,
    first_name: `User`,
    last_name: `${i}`,
    job_title: ["Trader", "Analyst", "Manager", "Director"][i % 4],
    status: i % 5 === 0 ? "Inactive" : "Active",
    last_login_at: new Date(2024, 2, i).toISOString(),
    roles: ["ROLE_TRADER"],
  });
}
