import { useVaultSiteStore } from "@/store/vaultSiteStore";

export const useVaultSite = () => {
  const {
    vaultSites,
    vaultSiteDetails,
    vaults,
    inventorySummary,
    inventoryByOwner,
    inventoryByProductType,
    inventoryByVault,
    totalCount,
    offset,
    limit,
    country,
    loading,
    error,
    vaultsLoading,
    vaultsError,
    inventoryLoading,
    inventoryError,
    filters,
    fetchVaultSites,
    fetchVaultSiteById,
    createVaultSite,
    fetchVaultsByVaultSiteId,
    fetchVaultSiteInventory,
    setCountry,
    setOffset,
    setLimit,
    setFilters,
    resetFilters,
    resetVaultSiteDetails,
  } = useVaultSiteStore();

  return {
    vaultSites,
    vaultSiteDetails,
    vaults,
    inventorySummary,
    inventoryByOwner,
    inventoryByProductType,
    inventoryByVault,
    totalCount,
    offset,
    limit,
    country,
    loading,
    error,
    vaultsLoading,
    vaultsError,
    inventoryLoading,
    inventoryError,
    filters,
    fetchVaultSites,
    fetchVaultSiteById,
    createVaultSite,
    fetchVaultsByVaultSiteId,
    fetchVaultSiteInventory,
    setCountry,
    setOffset,
    setLimit,
    setFilters,
    resetFilters,
    resetVaultSiteDetails,
  };
};
