import { useVaultSiteStore } from "@/store/vaultSiteStore";

export const useVaultSite = () => {
  const {
    vaultSites,
    vaultSiteDetails,
    vaults,
    inventorySummary,
    inventoryByOwner,
    inventoryByProductType,
    inventoryByVault,
    totalCount,
    offset,
    limit,
    country,
    loading,
    error,
    fetchVaultSites,
    fetchVaultSiteById,
    createVaultSite,
    fetchVaultsByVaultSiteId,
    fetchVaultSiteInventory,
    setCountry,
    setOffset,
    setLimit,
    resetVaultSiteDetails,
  } = useVaultSiteStore();

  return {
    vaultSites,
    vaultSiteDetails,
    vaults,
    inventorySummary,
    inventoryByOwner,
    inventoryByProductType,
    inventoryByVault,
    totalCount,
    offset,
    limit,
    country,
    loading,
    error,
    fetchVaultSites,
    fetchVaultSiteById,
    createVaultSite,
    fetchVaultsByVaultSiteId,
    fetchVaultSiteInventory,
    setCountry,
    setOffset,
    setLimit,
    resetVaultSiteDetails,
  };
};
